stages:
  - create
  - destroy

create-infraestructure-do:
  image: hashicorp/terraform:1.3.6
  stage: create
  script:
    - terraform -chdir="./modules/k8s-digital-ocean" init  -backend-config="conn_str=${TF_PG_CONN}" -backend-config="schema_name=do_$BACKEND_SCHEMA"
    - terraform -chdir="./modules/k8s-digital-ocean" apply -auto-approve
  rules:
    - if: $PROVIDER == "digitalocean" && $BACKEND_SCHEMA && $ACTION == "create"
  retry: 2

destroy-infraestructure-do:
  image: hashicorp/terraform:1.3.6
  stage: destroy
  script:
    - terraform -chdir="./modules/k8s-digital-ocean" init  -backend-config="conn_str=${TF_PG_CONN}" -backend-config="schema_name=do_$BACKEND_SCHEMA"
    - terraform -chdir="./modules/k8s-digital-ocean" destroy -auto-approve
  rules:
    - if: $PROVIDER == "digitalocean" && $BACKEND_SCHEMA && $ACTION == "destroy"
  retry: 2

create-infraestructure-az:
  image: hashicorp/terraform:1.3.6
  stage: create
  script:
    - terraform -chdir="./modules/k8s-azure" init  -backend-config="conn_str=${TF_PG_CONN}" -backend-config="schema_name=az_$BACKEND_SCHEMA"
    - terraform -chdir="./modules/k8s-azure" apply -auto-approve
  rules:
    - if: $PROVIDER == "azure" && $BACKEND_SCHEMA && $ACTION == "create"
  retry: 2

destroy-infraestructure-az:
  image: hashicorp/terraform:1.3.6
  stage: destroy
  script:
    - terraform -chdir="./modules/k8s-azure" init  -backend-config="conn_str=${TF_PG_CONN}" -backend-config="schema_name=az_$BACKEND_SCHEMA"
    - terraform -chdir="./modules/k8s-azure" destroy -auto-approve
  rules:
    - if: $PROVIDER == "azure" && $BACKEND_SCHEMA && $ACTION == "destroy"
  retry: 2

create-infraestructure-vsphere:
  image: joealisson/haacs:kubespray.2.20-terraform
  stage: create
  script:
    - terraform -chdir="./modules/k8s-vsphere" init  -backend-config="conn_str=${TF_PG_CONN}" -backend-config="schema_name=vsphere_$BACKEND_SCHEMA"
    - terraform -chdir="./modules/k8s-vsphere" apply -auto-approve
  rules:
    - if: $PROVIDER == "vsphere" && $BACKEND_SCHEMA && $ACTION == "create"
  retry: 2

destroy-infraestructure-vsphere:
  image: joealisson/haacs:kubespray.2.20-terraform
  stage: destroy
  script:
    - terraform -chdir="./modules/k8s-vsphere" init  -backend-config="conn_str=${TF_PG_CONN}" -backend-config="schema_name=vsphere_$BACKEND_SCHEMA"
    - terraform -chdir="./modules/k8s-vsphere" destroy -auto-approve
  rules:
    - if: $PROVIDER == "vsphere" && $BACKEND_SCHEMA && $ACTION == "destroy"
  retry: 2

