variables:
  DIR: ./modules/k8s-digital-ocean
  CHDIR: -chdir="${DIR}"

stages:
  - provisioning

creating-infraestructure-do:
  image: hashicorp/terraform:1.3.0
  stage: provisioning
  script:
    - terraform ${CHDIR} init  -backend-config="conn_str=${TF_PG_CONN}" -backend-config="schema_name=infra1"
    - terraform ${CHDIR} apply -auto-approve
  rules:
    - when: manual